#ifndef _TRENDER_COMMON_MOUSEBUTTONCODE_H_
#define _TRENDER_COMMON_MOUSEBUTTONCODE_H_

#define TR_MOUSE_BUTTON_1         0
#define TR_MOUSE_BUTTON_2         1
#define TR_MOUSE_BUTTON_3         2
#define TR_MOUSE_BUTTON_4         3
#define TR_MOUSE_BUTTON_5         4
#define TR_MOUSE_BUTTON_6         5
#define TR_MOUSE_BUTTON_7         6
#define TR_MOUSE_BUTTON_8         7
#define TR_MOUSE_BUTTON_LAST      TR_MOUSE_BUTTON_8
#define TR_MOUSE_BUTTON_LEFT      TR_MOUSE_BUTTON_1
#define TR_MOUSE_BUTTON_RIGHT     TR_MOUSE_BUTTON_2
#define TR_MOUSE_BUTTON_MIDDLE    TR_MOUSE_BUTTON_3

#endif //_TRENDER_COMMON_MOUSEBUTTONCODE_H_
